ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
obj-$(CONFIG_AK7345_ACT) += ak7345_act.o
obj-$(CONFIG_BU64241_ACT) += bu64241_act.o
obj-$(CONFIG_BU63164GWL_ACT) += bu63164gwl_act.o
